export const lineChart: string;
export const line: string;
export const yAxis: string;
export const xAxis: string;
export const tick: string;
export const tooltip: string;
export const number: string;
export const hoverBox: string;
export const hoverLine: string;
