version: '2'

services:
  frontend:
    image: node:9
    working_dir: /frontend
    command: npm run development
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
  backend:
    image: node:9
    working_dir: /backend
    command: npm start
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: ${NODE_ENV}