export const actionTypes = {
  REQUEST_TEMPERATURE: 'ENTITIES/REQUEST_TEMPERATURE',
  REQUEST_PRECIPITATION: 'ENTITIES/REQUEST_PRECIPITATION',
  REQUEST_TEMPERATURE_SUCCESS: 'ENTITIES/REQUEST_TEMPERATURE_SUCCESS',
  REQUEST_PRECIPITATION_SUCCESS: 'ENTITIES/REQUEST_PRECIPITATION_SUCCESS'
}